name: Sync tokens.theme.json to GitLab

on:
  push:
    paths:
      - tokens.theme.json
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone GitLab repo
        env:
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
        run: |
          git clone http://${GITLAB_USERNAME}:${GITLAB_TOKEN}@${GITLAB_REPO#http://} gitlab-repo
          cp tokens.theme.json gitlab-repo/
          cd gitlab-repo
          git add tokens.theme.json
          git commit -m "Sync tokens.theme.json from GitHub"
          git push origin main
